export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOG_OUT: 'LOG_OUT',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',

  GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILED: 'GET_USER_DATA_FAILED',

  GET_ALL_USER_DATA_REQUEST: 'GET_ALL_USER_DATA_REQUEST',
  GET_ALL_USER_DATA_SUCCESS: 'GET_ALL_USER_DATA_SUCCESS',
  GET_ALL_USER_DATA_FAILED: 'GET_ALL_USER_DATA_FAILED',

  UPDATE_USER_DATA_REQUEST: 'UPDATE_USER_DATA_REQUEST',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
  UPDATE_USER_DATA_FAILED: 'UPDATE_USER_DATA_FAILED',

  FORGOT_PASS_REQUEST: 'FORGOT_PASS_REQUEST',
  FORGOT_PASS_SUCCESS: 'FORGOT_PASS_SUCCESS',
  FORGOT_PASS_FAILED: 'FORGOT_PASS_FAILED',

  GET_PLACE_REQUEST: 'GET_PLACE_REQUEST',
  GET_PLACE_SUCCESS: 'GET_PLACE_SUCCESS',
  GET_PLACE_FAILED: 'GET_PLACE_FAILED',

  GET_TOURS_REQUEST: 'GET_TOURS_REQUEST',
  GET_TOURS_SUCCESS: 'GET_TOURS_SUCCESS',
  GET_TOURS_FAILED: 'GET_TOURS_FAILED',

  SEARCH_TOURS_REQUEST: 'SEARCH_TOURS_REQUEST',
  SEARCH_TOURS_SUCCESS: 'SEARCH_TOURS_SUCCESS',
  SEARCH_TOURS_FAILED: 'SEARCH_TOURS_FAILED',

  BOOKING_TOURS_REQUEST: 'BOOKING_TOURS_REQUEST',
  BOOKING_TOURS_SUCCESS: 'BOOKING_TOURS_SUCCESS',
  BOOKING_TOURS_FAILED: 'BOOKING_TOURS_FAILED',

  LIST_BOOKING_ALL_REQUEST: 'LIST_BOOKING_ALL_REQUEST',
  LIST_BOOKING_ALL_SUCCESS: 'LIST_BOOKING_ALL_SUCCESS',
  LIST_BOOKING_ALL_FAILED: 'LIST_BOOKING_ALL_FAILED',

  LIST_BOOKING_BY_ID_USER_REQUEST: 'LIST_BOOKING_BY_ID_USER_REQUEST',
  LIST_BOOKING_BY_ID_USER_SUCCESS: 'LIST_BOOKING_BY_ID_USER_SUCCESS',
  LIST_BOOKING_BY_ID_USER_FAILED: 'LIST_BOOKING_BY_ID_USER_FAILED',

  CANCEL_BOOKING_TOURS_REQUEST: 'CANCEL_BOOKING_TOURS_REQUEST',
  CANCEL_BOOKING_TOURS_SUCCESS: 'CANCEL_BOOKING_TOURS_SUCCESS',
  CANCEL_BOOKING_TOURS_FAILED: 'CANCEL_BOOKING_TOURS_FAILED',
};
