export default {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOG_OUT: 'LOG_OUT',

  SIGN_UP_REQUEST: 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',

  GET_USER_DATA_REQUEST: 'GET_USER_DATA_REQUEST',
  GET_USER_DATA_SUCCESS: 'GET_USER_DATA_SUCCESS',
  GET_USER_DATA_FAILED: 'GET_USER_DATA_FAILED',

  UPDATE_USER_DATA_REQUEST: 'UPDATE_USER_DATA_REQUEST',
  UPDATE_USER_DATA_SUCCESS: 'UPDATE_USER_DATA_SUCCESS',
  UPDATE_USER_DATA_FAILED: 'UPDATE_USER_DATA_FAILED',

  GET_PROVINCE_REQUEST: 'GET_PROVINCE_REQUEST',
  GET_PROVINCE_SUCCESS: 'GET_PROVINCE_SUCCESS',
  GET_PROVINCE_FAILED: 'GET_PROVINCE_FAILED',

  GET_TOUR_REQUEST: 'GET_TOUR_REQUEST',
  GET_TOUR_SUCCESS: 'GET_TOUR_SUCCESS',
  GET_TOUR_FAILED: 'GET_TOUR_FAILED',
};
